# Generated by Django 6.0.3 on 2026-04-11 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movies_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.URLField(max_length=500),
        ),
    ]
