# Generated by Django 6.0.4 on 2026-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movies_is_serie_alter_movies_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
