# Generated by Django 6.0.4 on 2026-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movies_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
